### PR TITLE
Adding frontend, Basic Navbar

### PR DESCRIPTION
**Pull request by KaranSinghBisht**
**Fix Issue #5 **<br>
I have added a basic front end temple using react (create-react-app)

**Description**<br>
I have added a simple navbar

**Type of change**<br>
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

**Checks**<br>

- [x] The PR to the branch is as mentioned in the issue

### CODE REVIEW

**Comment by malakar-soham** [comment]
Please attach an image of how the webpage looks

**Comment by KaranSinghBisht** [comment]
WebViewHover
MobileViewClosed
WebView
MobileViewOpen
MobileViewClick

**Comment by malakar-soham** [comment]
image

*I'm getting this page only*<br>
Steps I followed:
- Moved to the directory of the app
- npm install
- npm start

**Comment by KaranSinghBisht** [comment]
make sure you have cd into the frontend (cd frontend) and then npm install
i think you npm install in the ez folder

**Comment by malakar-soham** [comment]
Cool ! It's running now

**Comment by KaranSinghBisht** [comment]
Done 😄

**Pull request merged**
