### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by rexdivakar**
**Fixes issue** <br>
*Refer to the related issue using #[issue_number]*

**Description**<br>
*A short description of the changes that have been introduced*

**Type of change**<br>
*Put an `x` in the boxes that apply*
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

**Checks**<br>
*Put an `x` in the boxes that apply*
- [x] The PR to the branch is as mentioned in the issue

### CODE REVIEW

**Comment by malakar-soham** [comment]
Please edit the template , in the meantime I'll add a reviewer

**Comment by rexdivakar** [comment]
Upadated @malakar-soham

**Comment by shoumikdey** [comment]
Hi @rexdivakar Can you please attach a working gif of the DB code. Also the db should be empty that you have attached with this PR, please confirm that.

**Comment by rexdivakar** [comment]
The database code is just 3 lines, do u want a snap of it ??

**Comment by rexdivakar** [comment]
@shoumikdey  please respond !!

**Comment by shoumikdey** [comment]
> @shoumikdey please respond !!

Check #38

**Pull request closed without merging**
