### PR TITLE
Added word list

### PR DESCRIPTION
**Pull request by rexdivakar**
**Fixes issue** <br>
#11 

**Description**<br>
*A short description of the changes that have been introduced*

**Type of change**<br>
- [] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

**Checks**<br>
- [x] The PR to the branch is as mentioned in the issue

### CODE REVIEW

**Comment by malakar-soham** [comment]
Please edit the template completely and refrain from using SnapChat acronyms 😄 , just any term related to the gaming world

**Comment by rexdivakar** [comment]
So u think these below terms don't belong to gaming world ??

FG | Fighting Games | Self Explanatory
mk | hm okay | Self Explanatory
O.G. | Original Gamer | Self Explanatory
MMO | Massively Multiplayer Online | Massive arena of players online for gaming
MP | Magic Points | reward points awarded during a game
FPS | First Person Shooter | Self Explanatory
RPG | Role-Playing Game | Self Explanatory
WC | Wrong Chat | Self Explanatory
FF | Forfeit | Cheating in a game
Gz | Congratulations | Self Explanatory
OT | Off Tank | Self Explanatory
PvP | Player vs Player | Self Explanatory
TPS | Third Person Shooter | Self Explanatory
RTS | Real Time Strategy | Self Explanatory
TBS | Turn Based Strategy | Self Explanatory
BR | Battle Royale | Arena of players against each other ex: PUBG
MOBA | Multiplayer Online Battle Arena | Self Explanatory
MMO | Massively Multiplayer Online | Self Explanatory
TCG/CCG | Trading/Collectible Card Game | Self Explanatory
P2W | Pay To Win | Stratergy towards wining a game
LoS | Line of Sight | reference towards target in sight
DOT | Damage Over Time | Self Explanatory
MVP | Most Valuable Player | Self Explanatory

**Comment by malakar-soham** [comment]
I meant only a few:

```
mk | hm okay | Self Explanatory
O.G. | Original Gamer | Self Explanatory
```
I think people use the full words for these:

```
TBS | Turn Based Strategy | Self Explanatory
BR | Battle Royale | Arena of players against each other ex: PUBG
```
This is repeated twice:
`MMO | Massively Multiplayer Online | Self Explanatory`

Please edit your PR accordingly , edit the 1st comment(template) and I will merge it 👍

**Comment by rexdivakar** [comment]
oh k will make changes  @malakar-soham

**Review by rexdivakar — COMMENTED** [review]
Updated terms

**Comment by rexdivakar** [comment]
Hey @malakar-soham 
As you know Hactobesfest rule is change
in Repo: Hactobesfest label and
in PR: Hactobesfest-accepted label should be there then It will count

In my PR Hactobesfest-accepted are show if can Please can u change the labels !! Also validate my work and close this PR

**Comment by malakar-soham** [comment]
By default it's accepted if it is merged as per the rules changes on 3rd October. This PR was submitted and merged before 3rd, so by default its accepted, don't worry about that 👍

**Comment by rexdivakar** [comment]
hey @malakar-soham  can u please add in the labels, my PR is not validated yet

**Comment by malakar-soham** [comment]
Please write a comment on the PRs I'll look into the matter

**Pull request merged**
