### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by rexdivakar**
**Fixes issue** <br>
*Refer to the related issue using #[issue_number]*

**Description**<br>
*A short description of the changes that have been introduced*

**Type of change**<br>
*Put an `x` in the boxes that apply*
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

**Checks**<br>
*Put an `x` in the boxes that apply*
- [x] The PR to the branch is as mentioned in the issue

### CODE REVIEW

**Comment by rexdivakar** [comment]
Database Docs:
image
image

**Comment by rexdivakar** [comment]
@malakar-soham @shoumikdey  Please validate the changes and close the Issue so it gets updated

**Comment by shoumikdey** [comment]
db

Hi @rexdivakar row 1 and 2 shouldn't be inserted into the DB. Also, it would be good if the file object is closed after the job is done. Thanks and cheers!

**Comment by rexdivakar** [comment]
Hope things are done, can u please approve it and close the issue !! @shoumikdey  @malakar-soham  @malakar-swastik

**Comment by rexdivakar** [comment]
@shoumikdey  the file object is not an issue as its been using with function  and data load part i have fixed it so it will skip first two rows before inserting them

**Comment by malakar-soham** [comment]
Good Job :+1:

**Pull request merged**
